version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- echo $AWS_DEFAULT_REGION
      #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 850769113977.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t kalyandocker .
      - docker tag kalyandocker:latest 850769113977.dkr.ecr.us-east-1.amazonaws.com/kalyandocker:latest
      #- docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push 850769113977.dkr.ecr.us-east-1.amazonaws.com/kalyandocker:latest
      - printf '[{"name":"kalyan","imageUri":"121272337069.dkr.ecr.us-east-2.amazonaws.com/node-api:latest"}]' > imagedefinitions.js
      #- echo Writing image definitions file...
      #- printf '[{"name":"kalyan","imageUri":"%s"}]' 850769113977.dkr.ecr.us-east-1.amazonaws.com/sampledocker:latest > imagedefinitions.json
      #- cat imagedefinitions.json 
      #- zip -r imagedefinitions.json.zip imagedefinitions.json
      #- aws s3 cp ./imagedefinitions.json.zip s3://codepipeline-us-east-1-457832133121
      # docker
   artifacts:
    files:
      - imagedefinitions.json
#artifacts:
    #files: imagedefinitions.json
